/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.strutsLogin.action;

import java.util.ResourceBundle;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.strutsLogin.form.BaseForm;
import org.apache.log4j.*;
public abstract class BaseAction extends Action {
	private static Logger logger =Logger.getLogger(BaseAction.class);
	protected ResourceBundle resourceBundle = null;

	public void init() {
		resourceBundle = ResourceBundle
				.getBundle("com.strutsLogin.resource.ApplicationResources");
	}

	public final ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		init();
		
		BaseForm formBean = (BaseForm) form;
		if(formBean==null)
			System.out.println("Null value in base form");
		else
			System.out.println("It is in baseform and formbean="+formBean.toString());
		logger.error("Base From Form bean " + formBean);

		String operation = formBean.getOperation();
		if(operation== null)
			System.out.println("Operation is null");
		else
			System.out.println("operation is not null");
		// if (!"Login".equals(operation)) {
		//
		// UserDTO userDTO = (UserDTO) request.getSession().getAttribute(
		// "userDTO");
		//
		// if (userDTO == null) {
		// actionForward = mapping.findForward("Logout");
		// return actionForward;
		// }
		// }

		// Call chields fdtsExecute
		if (mapping.getPath().toLowerCase().indexOf("display") != -1) {
			formBean.setDisplay(true);
		} else {
			formBean.setDisplay(false);
			System.out.println();
			System.out.println("In else part of mapping getpath condition");
		}

		// Debug statements
		logger.error("Action Path :\n" + mapping.getPath());
		logger.error("Action : \n" + this.getClass().getName());
		logger.error("Is Display  :\n" + formBean.isDisplay());
		logger.error("Operation   :\n" + formBean.getOperation());
		
		
		ActionForward actionForward = null;

		if (formBean.isDisplay()) {
			actionForward = display(mapping, formBean, operation, request,
					response);
			System.out.println("\nIn I part of formbeanisdisplay");
		} else {
			System.out.println("\nIn else part of formbeanisdisplay b4 submit");
			
			actionForward = submit(mapping, formBean, operation, request,response);
			System.out.println("\nIn else part of formbeanisdisplay a4 \n value of actionForward="+actionForward);			
		}

		// System.out.println("actionForward Path :" + actionForward.getPath());
		// System.out.println("actionForward Name :" + actionForward.getName());
		// System.out.println("actionForward Module :" +
		// actionForward.getModule());

		if (actionForward == null) {
			actionForward = mapping.findForward("UnderCunstruction");
			System.out.println("\nactionforawrd is null");
		}
		
		System.out.println("\nForwarding to :" + actionForward.getName());
		return actionForward;
	}

	/*
	 * This method will contain actual navigation logic for individual usecases.
	 * It must be overridden by child action classes
	 */

	public abstract ActionForward submit(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response);

	public abstract ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response);
}