/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.strutsLogin.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.strutsLogin.delegate.BusinessUnitMasterServiceDelegate;
import com.strutsLogin.dto.BusinessUnitMasterDTO;

import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.BusinessUnitMasterForm;
import com.strutsLogin.util.DataUtil;


/**
 * MyEclipse Struts Creation date: 08-08-2006
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/hospital" name="hospitalForm" input="/hospital.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class BusinessUnitMasterAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward submit(ActionMapping mapping,
			BaseForm form, String operation, HttpServletRequest request,
			HttpServletResponse response) {

		BusinessUnitMasterForm BusinessUnitMasterForm = (BusinessUnitMasterForm) form;

		
		BusinessUnitMasterDTO dto = null;

		if ("Add".equals(operation)) {
			
			dto = (BusinessUnitMasterDTO) BusinessUnitMasterForm.getDTO();
			BusinessUnitMasterServiceDelegate.add(dto);
			
			
			
			
			
	} else if ("Delete".equals(operation)) {
			dto = (BusinessUnitMasterDTO) BusinessUnitMasterForm.getDTO();
			BusinessUnitMasterServiceDelegate.delete(dto);
			
	} else if ("Update".equals(operation)) {
			
			dto = (BusinessUnitMasterDTO) BusinessUnitMasterForm.getDTO();
	
			BusinessUnitMasterServiceDelegate.update(dto);
	}
	 else if("Cancel".equals(operation)){
		 return mapping.findForward("BusinessUnitMasterList");
	}

		return mapping.findForward("BusinessUnitMasterList");
	}

	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		
		BusinessUnitMasterForm BusinessUnitMasterForm = (BusinessUnitMasterForm) form;
		
		if(BusinessUnitMasterForm.getBusinessUnitId() != null){
			BusinessUnitMasterDTO dto = BusinessUnitMasterServiceDelegate.get(DataUtil.getInteger(BusinessUnitMasterForm.getBusinessUnitId()));
			BusinessUnitMasterForm.populate(dto);
		}

		return mapping.findForward("Success");

	}

}
