/*
 * Generated by Nenosystems Generator Struts
 */

package com.strutsLogin.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.strutsLogin.delegate.BusinessPerfPlanServiceDelegate;
import com.strutsLogin.delegate.BusinessUnitMasterServiceDelegate;
import com.strutsLogin.delegate.OaipServiceDelegate;
import com.strutsLogin.dto.BusinessPerfPlanDTO;
import com.strutsLogin.dto.BusinessUnitMasterDTO;
import com.strutsLogin.dto.SearchCriteria;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.BusinessPerfPlanForm;
import com.strutsLogin.form.BusinessPerfPlanListForm;
import com.strutsLogin.form.BusinessUnitMasterForm;
import com.strutsLogin.form.BusinessUnitMasterListForm;
import com.strutsLogin.form.OaipListForm;
import com.strutsLogin.form.OaipListYearlyForm;
import com.strutsLogin.util.DataUtil;

public class BusinessPerfPlanListAction extends BaseAction {


	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		
		BusinessPerfPlanListForm listForm = new BusinessPerfPlanListForm();
		return mapping.findForward("Success");
		
	}

	@Override
	public ActionForward submit(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {

 BusinessPerfPlanDTO dto= null;
	     
	     if("Delete".equals(operation)){
	    		BusinessPerfPlanListForm listForm = (BusinessPerfPlanListForm) form;
				dto = (BusinessPerfPlanDTO) listForm.getDTO();
				BusinessPerfPlanServiceDelegate.delete(dto);
				
				//After Delete
				BusinessPerfPlanListForm listForm1 = new BusinessPerfPlanListForm();
				List list1 = null;

				SearchCriteria criteria = new SearchCriteria();
				criteria.setOrderBy(listForm1.getOrderBy());
				criteria.setAsc(listForm1.isAsc());

				list1 = BusinessPerfPlanServiceDelegate.getList(criteria);

				listForm1.setList(list1);
				 request.setAttribute("list1", list1);
	     }
				 //
	     if("OK".equals(operation)){
	    	// BusinessPerfPlanForm businessUnitMasterForm =(BusinessPerfPlanForm) form;
	    		BusinessPerfPlanListForm listForm = (BusinessPerfPlanListForm) form;
				List list1 = null;
				int bunit=DataUtil.getInteger(listForm.getBusinessUnitId());
				System.out.println("Value of Action"+bunit);
				list1 = BusinessPerfPlanServiceDelegate.getBunit(bunit);
				System.out.println("size of list"+list1.size());
				listForm.setList(list1);
				 request.setAttribute("list1", list1);
		 
		return mapping.findForward("Success");
	
		 }
				 //
			
		

	return mapping.findForward("Success");
}

}
