/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.strutsLogin.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.strutsLogin.delegate.CountryMasterServiceDelegate;
import com.strutsLogin.dto.CountryMasterDTO;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.CountryMasterForm;
import com.strutsLogin.util.DataUtil;



/**
 * MyEclipse Struts Creation date: 08-08-2006
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/hospital" name="hospitalForm" input="/hospital.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class CountryMasterAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward submit(ActionMapping mapping,
			BaseForm form, String operation, HttpServletRequest request,
			HttpServletResponse response) {

		CountryMasterForm CountryMasterForm = (CountryMasterForm) form;

		
		CountryMasterDTO dto = null;

		if ("Add".equals(operation)) {
			
			dto = (CountryMasterDTO) CountryMasterForm.getDTO();
			
			CountryMasterServiceDelegate.add(dto);
			
	} else if ("Delete".equals(operation)) {
			dto = (CountryMasterDTO) CountryMasterForm.getDTO();
			CountryMasterServiceDelegate.delete(dto);
			
	} else if ("Update".equals(operation)) {
			
			dto = (CountryMasterDTO) CountryMasterForm.getDTO();
			
			CountryMasterServiceDelegate.update(dto);
	}

		return mapping.findForward("CountryMasterList");
	}

	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		
		CountryMasterForm CountryMasterForm = (CountryMasterForm) form;
		
		if(CountryMasterForm.getCountryId() != null){
			CountryMasterDTO dto = CountryMasterServiceDelegate.get(DataUtil.getInteger(CountryMasterForm.getCountryId()));
			CountryMasterForm.populate(dto);
		}

		return mapping.findForward("Success");

	}

}
