/*
 * Generated by Nenosystems Generator Struts
 */

package com.strutsLogin.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.strutsLogin.delegate.CountryMasterServiceDelegate;

import com.strutsLogin.dto.CountryMasterDTO;

import com.strutsLogin.dto.SearchCriteria;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.CountryMasterForm;
import com.strutsLogin.form.CountryMasterListForm;




public class CountryMasterListAction extends BaseAction {


	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		CountryMasterListForm listForm = (CountryMasterListForm) (form);
		List list1 = null;

		SearchCriteria criteria = new SearchCriteria();
		criteria.setOrderBy(listForm.getOrderBy());
		criteria.setAsc(listForm.isAsc());

		list1 = CountryMasterServiceDelegate.getList(criteria);

		listForm.setList(list1);
		 request.setAttribute("list1", list1);
		
		
		System.out.println("list of country>>>>>>>>>>>>>>>>>>>>>"+list1.size());

		return mapping.findForward("Success");
	}

	@Override
	public ActionForward submit(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		 CountryMasterDTO dto= null;
	     
	     if("Delete".equals(operation)){
				CountryMasterForm countryMasterForm =(CountryMasterForm) form;
				dto = (CountryMasterDTO) countryMasterForm.getDTO();
				//this is operation of Delete Method
				CountryMasterServiceDelegate.delete(dto);
				
				//After Delete
				CountryMasterListForm listForm = new CountryMasterListForm();
				List list1 = null;

				SearchCriteria criteria = new SearchCriteria();
				criteria.setOrderBy(listForm.getOrderBy());
				criteria.setAsc(listForm.isAsc());

				list1 = CountryMasterServiceDelegate.getList(criteria);

				listForm.setList(list1);
				 request.setAttribute("list1", list1);
			
		}


	return mapping.findForward("Success");
}


}
