/*
 * Generated by Vikas Vasnik Generator Struts
 */

package com.strutsLogin.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.strutsLogin.delegate.EmployeeMasterServiceDelegate;
import com.strutsLogin.dto.EmployeeMasterDTO;
import com.strutsLogin.dto.SearchCriteria;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.EmployeeMasterForm;
import com.strutsLogin.form.EmployeeMasterListForm;

public class EmployeeMasterListAction extends BaseAction {


	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		EmployeeMasterListForm listForm = (EmployeeMasterListForm) (form);
		List list1 = null;

		SearchCriteria criteria = new SearchCriteria();
		criteria.setOrderBy(listForm.getOrderBy());
		criteria.setAsc(listForm.isAsc());

		list1 = EmployeeMasterServiceDelegate.getList(criteria);

		listForm.setList(list1);
		 request.setAttribute("list1", list1);

		return mapping.findForward("Success");
	}

	@Override
	public ActionForward submit(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {

		//     EmployeeMasterListForm listForm = (EmployeeMasterListForm) (form);
		     EmployeeMasterDTO dto= null;
		     
		     if("Delete".equals(operation)){
					EmployeeMasterForm employeeMasterForm1 =(EmployeeMasterForm) form;
					dto = (EmployeeMasterDTO) employeeMasterForm1.getDTO();
					EmployeeMasterServiceDelegate.delete(dto);
					
					//After Delete
					EmployeeMasterListForm listForm = new EmployeeMasterListForm();
					List list1 = null;

					SearchCriteria criteria = new SearchCriteria();
					criteria.setOrderBy(listForm.getOrderBy());
					criteria.setAsc(listForm.isAsc());

					list1 = EmployeeMasterServiceDelegate.getList(criteria);

					listForm.setList(list1);
					 request.setAttribute("list1", list1);
				
			}


		return mapping.findForward("Success");
	}


}
