/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.strutsLogin.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import com.strutsLogin.delegate.EmployeePerformanceServiceDelegate;
import com.strutsLogin.dto.EmployeePerformanceDTO;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.EmployeePerformanceForm;
import com.strutsLogin.util.DataUtil;

/**
 * MyEclipse Struts Creation date: 08-08-2006
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/hospital" name="hospitalForm" input="/hospital.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class EmployeePerformanceAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward submit(ActionMapping mapping,
			BaseForm form, String operation, HttpServletRequest request,
			HttpServletResponse response) {

		EmployeePerformanceForm employeePerformanceForm = (EmployeePerformanceForm) form;

		
		EmployeePerformanceDTO dto = null;

		if ("Add".equals(operation)) {
			
			dto = (EmployeePerformanceDTO) employeePerformanceForm.getDTO();
			EmployeePerformanceServiceDelegate.add(dto);
			
	} else if ("Delete".equals(operation)) {
			dto = (EmployeePerformanceDTO) employeePerformanceForm.getDTO();
			EmployeePerformanceServiceDelegate.delete(dto);
			
	} 
	
	else if ("Update".equals(operation)) {
			
			dto = (EmployeePerformanceDTO) employeePerformanceForm.getDTO();
			
			EmployeePerformanceServiceDelegate.update(dto);
	}

		return mapping.findForward("Success");
	}

	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		
		EmployeePerformanceForm employeePerformanceForm = (EmployeePerformanceForm) form;
		
		if(employeePerformanceForm.getEmpId() != null){
			EmployeePerformanceDTO dto = EmployeePerformanceServiceDelegate.get(DataUtil.getInteger(employeePerformanceForm.getEmpId()));
			employeePerformanceForm.populate(dto);
		}

		return mapping.findForward("Success");

	}

}
