/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.strutsLogin.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;



import com.strutsLogin.form.LavarageForm;
import com.strutsLogin.delegate.LavarageServiceDelegate;
import com.strutsLogin.dto.LavarageDTO;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.util.DataUtil;

 
public class LavarageAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward submit(ActionMapping mapping,
			BaseForm form, String operation, HttpServletRequest request,
			HttpServletResponse response) {

		LavarageForm LavarageForm = (LavarageForm) form;

		
		LavarageDTO dto = null;

		if ("Add".equals(operation)) {
			
			dto = (LavarageDTO) LavarageForm.getDTO();
			
			LavarageServiceDelegate.add(dto);
			
	} else if ("Delete".equals(operation)) {
			dto = (LavarageDTO) LavarageForm.getDTO();
			LavarageServiceDelegate.delete(dto);
			
	} else if ("Update".equals(operation)) {
			
			dto = (LavarageDTO) LavarageForm.getDTO();
			
			LavarageServiceDelegate.update(dto);
	}

		return mapping.findForward("LavarageList");
	}

	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		
		LavarageForm LavarageForm = (LavarageForm) form;
		
		if(LavarageForm.getLeverageId() != null){
			LavarageDTO dto = LavarageServiceDelegate.get(DataUtil.getInteger(LavarageForm.getLeverageId()));
			LavarageForm.populate(dto);
		}

		return mapping.findForward("Success");

	}

}
