/*
 * Generated by Nenosystems Generator Struts
 */

package com.strutsLogin.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Criteria;


import com.strutsLogin.delegate.CountryMasterServiceDelegate;
import com.strutsLogin.delegate.EmployeeMasterServiceDelegate;
import com.strutsLogin.delegate.OaipServiceDelegate;
//import com.strutsLogin.delegate.OaipServiceYearlyDelegate;
import com.strutsLogin.dto.EmployeeMasterDTO;
import com.strutsLogin.dto.SearchCriteria;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.CountryMasterListForm;
import com.strutsLogin.form.EmployeeMasterForm;
import com.strutsLogin.form.EmployeeMasterListForm;
import com.strutsLogin.form.OaipListForm;
import com.strutsLogin.form.OaipListYearlyForm;
import com.strutsLogin.util.DataUtil;

public class OaipListActionYearly extends BaseAction {

	
	private String empId;
	
	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		OaipListYearlyForm listForm = (OaipListYearlyForm) (form);

		return mapping.findForward("Success");
	}

	@Override
	public ActionForward submit(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		
		EmployeeMasterDTO dto;
	
		// TODO Auto-generated method stub
		 if("OK".equals(operation)){
			 OaipListYearlyForm oaipListFormYearly =(OaipListYearlyForm) form;
			
				List list1 = null;

				int year=oaipListFormYearly.getYear();
				System.out.println("Value of Action"+year);
				
				int bunit=oaipListFormYearly.getBusinessUnitId();
				System.out.println("Value of Action"+bunit);
				
				list1 = OaipServiceDelegate.getcal(year,bunit);
			
				System.out.println("size of list"+list1.size());
			//	oaipListFormYearly.setList(list1);
				 request.setAttribute("list1", list1);
		 
		return mapping.findForward("Success");
	
		 }

		 if ("Calculate".equals(operation)) {
				EmployeeMasterDTO employeeMasterDTO = new EmployeeMasterDTO();
				OaipListForm oaipListForm1 =(OaipListForm) form;
				List list1 = null;
				System.out.println("inside CALCULATE if....");
				
					OaipListForm oaipListForm2 =(OaipListForm) form;
					
		   		    System.out.println("in calculate ------------------");
				    oaipListForm2.setEmpId(empId);
				   
					System.out.println("action emp id is .............."+oaipListForm2.getEmpId());
					String empId=oaipListForm2.getEmpId();
					list1 =OaipServiceDelegate.getCalculate(DataUtil.getInteger(empId));
				
				  oaipListForm1.setList(list1);
				 request.setAttribute("list1", list1);
				
			 return mapping.findForward("Success");
			}
			return mapping.findForward("Success");
			}
			}	


