/*
 * Generated by Nenosystems Generator Struts
 */

package com.strutsLogin.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Criteria;


import com.strutsLogin.delegate.CountryMasterServiceDelegate;
import com.strutsLogin.delegate.EmployeeMasterServiceDelegate;
import com.strutsLogin.delegate.OaipServiceDelegate;
import com.strutsLogin.dto.EmployeeMasterDTO;
import com.strutsLogin.dto.SearchCriteria;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.CountryMasterListForm;
import com.strutsLogin.form.EmployeeMasterForm;
import com.strutsLogin.form.EmployeeMasterListForm;
import com.strutsLogin.form.OaipListForm;
import com.strutsLogin.util.DataUtil;
public class OaipListAction extends BaseAction {

	
	private String empId;
	
	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		OaipListForm listForm = (OaipListForm) (form);

		return mapping.findForward("Success");
	}

	@Override
	public ActionForward submit(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		
		EmployeeMasterDTO dto;
	
		// TODO Auto-generated method stub
		 if("OK".equals(operation)){
			 OaipListForm oaipListForm =(OaipListForm) form;
			
				List list1 = null;

				int year=oaipListForm.getYear();
				System.out.println("Value of Action"+year);
				
				int month=oaipListForm.getMonth();
				System.out.println("Value of Action"+month);
				
				
				int bunit=oaipListForm.getBusinessUnitId();
				System.out.println("Value of Action"+bunit);
				
				list1 = OaipServiceDelegate.getDateOfJoining(year,month,bunit);
			
				System.out.println("size of list"+list1.size());
				oaipListForm.setList(list1);
				 request.setAttribute("list1", list1);
		 
		return mapping.findForward("Success");
	
		 }

		 if ("SAVE".equals(operation)) {
			 OaipListForm oaipListForm = (OaipListForm) form;
			 dto = (EmployeeMasterDTO) oaipListForm.getDTO();
				
				EmployeeMasterServiceDelegate.add(dto);
				
			 return mapping.findForward("Success");
			}
			return mapping.findForward("Success");
			}
			}	


