/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.strutsLogin.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.strutsLogin.delegate.PlanMasterServiceDelegate;
import com.strutsLogin.dto.PlanMasterDTO;
import com.strutsLogin.form.BaseForm;
import com.strutsLogin.form.PlanMasterForm;
import com.strutsLogin.util.DataUtil;



 
public class PlanMasterAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward submit(ActionMapping mapping,
			BaseForm form, String operation, HttpServletRequest request,
			HttpServletResponse response) {

		PlanMasterForm PlanMasterForm = (PlanMasterForm) form;

		
		PlanMasterDTO dto = null;

		if ("Add".equals(operation)) {
			
			dto = (PlanMasterDTO) PlanMasterForm.getDTO();
			
			PlanMasterServiceDelegate.add(dto);
			
	} 
			
	 else if ("Update".equals(operation)) {
			
			dto = (PlanMasterDTO) PlanMasterForm.getDTO();
			
			PlanMasterServiceDelegate.update(dto);
	}

		return mapping.findForward("PlanMasterList");
	}

	@Override
	public ActionForward display(ActionMapping mapping, BaseForm form,
			String operation, HttpServletRequest request,
			HttpServletResponse response) {
		
		PlanMasterForm PlanMasterForm = (PlanMasterForm) form;
		
		if(PlanMasterForm.getPlanId() != null){
			PlanMasterDTO dto = PlanMasterServiceDelegate.get(DataUtil.getInteger(PlanMasterForm.getPlanId()));
			PlanMasterForm.populate(dto);
		}

		return mapping.findForward("Success");

	}

}
